# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1374752136);
user_pref("app.update.lastUpdateTime.background-update-timer", 1374750739);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1374752256);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1374750499);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1374750619);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.buildID", "20130409194949");
user_pref("browser.startup.homepage_override.mstone", "20.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":3,\"passwords\":3}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1374836898470");
user_pref("datareporting.policy.firstRunTime", "1374750498470");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 568);
user_pref("datareporting.sessions.current.main", 53);
user_pref("datareporting.sessions.current.sessionRestored", 582);
user_pref("datareporting.sessions.current.startTime", "1374753680015");
user_pref("datareporting.sessions.current.totalTime", 30492);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.0", "{\"s\":1374750498249,\"a\":63,\"t\":332326,\"c\":true,\"m\":62,\"fp\":851,\"sr\":918}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1374751958362,\"a\":11,\"t\":52793,\"c\":true,\"m\":63,\"fp\":798,\"sr\":812}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1374752015434,\"a\":97,\"t\":771588,\"c\":true,\"m\":63,\"fp\":566,\"sr\":580}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1374752788104,\"a\":11,\"t\":52718,\"c\":true,\"m\":772,\"fp\":1474,\"sr\":1491}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1374752842175,\"a\":17,\"t\":814634,\"c\":true,\"m\":47,\"fp\":576,\"sr\":589}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1374753656695,\"a\":3,\"t\":21666,\"c\":true,\"m\":266,\"fp\":1026,\"sr\":1060}");
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "mitm-me%40andras.tim:2.1.110513,autoauth%40efinke.com:2.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:20.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}\",\"mtime\":1374735125129},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1368085211260}}},{\"name\":\"app-profile\",\"addons\":{\"autoauth@efinke.com\":{\"descriptor\":\"C:\\\\profile\\\\extensions\\\\autoauth@efinke.com.xpi\",\"mtime\":1374753657046},\"mitm-me@andras.tim\":{\"descriptor\":\"C:\\\\profile\\\\extensions\\\\mitm-me@andras.tim.xpi\",\"mtime\":1374751958515}}}]");
user_pref("extensions.lastAppVersion", "20.0.1");
user_pref("extensions.lastPlatformVersion", "20.0.1");
user_pref("extensions.mitm-me.silent_mode", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130409194949");
user_pref("gecko.mstone", "20.0.1");
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("idle.lastDailyNotification", 1374752391);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1374752391);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.cpd.sessions", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1374752391);
user_pref("toolkit.startup.last_success", 1374753680);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1377344930);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
